package com.hermes;


import com.hermes.utility.Parser;
import com.hermes.zookeeper.ZKManager;

public class Main {
    private static void printHelp() {
        System.out.println("Arguments: <zookeeper_url> <worker_host> <worker_port> [worker ID]");
        System.out.println("\t<zookeeper_url> : the URL of the ZooKeeper node, or comma separated URLs if multiple nodes");
        System.out.println("\t<worker_host> : URL or IP host name of this worker (e.g. localhost, 12.42.09.122)");
        System.out.println("\t<worker_port> : port this worker should listen on");
        System.out.println("\t[worker ID] : optional worker ID, will be autogenerated if not provided");
        System.out.println();
        System.out.println("Entering 'help' as an argument prints this help menu");
        System.out.println();
    }

    public static void main(String[] args) {
        if (args.length == 1 && "help".equals(args[0])) {
            printHelp();
            System.exit(1);
        }
        if (args.length < 3 || args.length > 4 || !Parser.isInt(args[2])) {
            System.out.println("Error - invalid arguments");
            printHelp();
            System.exit(1);
        }
        ZKManager.init(args[0]);
        Worker worker;
        if (args.length == 3) {
            worker = new Worker(args[1], Integer.parseInt(args[2]));
        } else {
            worker = new Worker(args[3], args[1], Integer.parseInt(args[2]));
        }
        worker.start();
    }
}
